#! /usr/bin/bash
#
# this is my left bar
# 

# COLOURS

CLOCK="$(getcolour 5)"
DESKTOP="$(getcolour 2)"
GITHUB="$(getcolour 8)"
FG="$(getcolour foreground)"
BG="$(getcolour background)"


# INFORMATION

Clock() {
    echo -n "%{B#FF"$CLOCK"} "
    TIME=$(date "+%H:%M:%S")
    echo -n "$TIME"
    echo -n " %{B-}"
}

Desktop() {
    echo -n "%{B#FF"$DESKTOP"}"
    DTOPS="$(bspc query -D | wc -l)"
    i=1
    while [ $i -le $DTOPS ]; do
        # check to see if any windows are open on that desktop
        #if [ -n "$(bspc query -W -d ^$i)" ]; then
        #    echo -n " "
        #else
        #    echo -n " %{F#FF"$BG"}"
        #fi
        # check to see if it is the focused desktop
        if [ "$(bspc query -D -d)" = "$(bspc query -D -d ^$i)" ]; then
            echo -n " #%{F-}"
        else
            echo -n " -%{F-}"
        fi
        
        let "i = $i + 1" 
    done
    echo -n " %{B-}"
}

# BAR

FONT="-*-terminus-medium-r-*-*-14-*-*-*-*-*-*-*"
x="10"
y="10"
w="2540"
h="20"
PARAMETERS="-f "$FONT" -g "$w"x"$h"+"$x"+"$y" -F #FF"$FG" -B #FF"$BG

while :; do echo "$(Desktop)%{r}$(Clock)"; done | bar $PARAMETERS
