#! /bin/sh

bspc config window_gap      12
bspc config border_width    4

bspc config top_padding         30
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config normal_border_color  '#'$(getcolour background) 
bspc config active_border_color  '#'$(getcolour background) 
bspc config focused_border_color '#'$(getcolour 5)
bspc config presel_border_color  '#'$(getcolour 12)
bspc config urgent_border_color  '#'$(getcolour 9)

bspc monitor DVI-D-0 -d Web Code Work Steam
bspc monitor HDMI-0 -d Media

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc rule -a csgo_linux desktop=Steam locked=on floating=on fullscreen=on
bspc rule -a 'War Thunder' desktop=Steam locked=on floating=on fullscreen=on
bspc rule -a steam.sh desktop=Steam
bspc rule -a steamwebhelper desktop=Steam
bspc rule -a ncmpcpp desktop=Media floating=on
bspc rule -a steamwebhelper floating=on
bspc rule -a steam desktop=Steam
bspc rule -a feh floating=on
bspc rule -a mpv desktop=Media floating=on 
bspc rule -a mupdf floating=on

feh --no-fehbg --bg-tile ~/Theming/Wallpapers/Other/dcleomenes.png
